[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "reRoute_Dynamics"
authors = [{name = "Sebastian Peck", email = "sebpeck@uw.edu"}]
dynamic = ["version", "description"]
